-- Migration 006: Async social features
-- Visits, Guilds, Guild Members

create type public.visit_type as enum (
  'passing',    -- brief encounter, no interaction
  'trade',      -- item exchange
  'duel',       -- friendly combat
  'memory_share' -- Eidolons share a memory
);

create type public.visit_status as enum (
  'pending',    -- waiting for host Eidolon to process
  'resolved',   -- processed on next session
  'declined'    -- host Eidolon declined
);

create table public.visits (
  id                    uuid primary key default gen_random_uuid(),
  visitor_eidolon_id    uuid not null references public.eidolons(id) on delete cascade,
  host_user_id          uuid not null references public.users(id) on delete cascade,
  visit_type            public.visit_type not null default 'passing',
  status                public.visit_status not null default 'pending',
  -- Interaction payload (type-specific data)
  payload               jsonb not null default '{}'::jsonb,
  -- Narrative generated by AI when resolved
  narrative             text,
  outcome               jsonb,
  created_at            timestamptz not null default now(),
  resolved_at           timestamptz
);

create index idx_visits_host_user_id       on public.visits(host_user_id, status);
create index idx_visits_visitor_eidolon_id on public.visits(visitor_eidolon_id);
create index idx_visits_created_at         on public.visits(created_at desc);

-- Guilds
create table public.guilds (
  id           uuid primary key default gen_random_uuid(),
  name         text not null unique,
  description  text,
  emblem       jsonb not null default '{}'::jsonb,
  max_members  smallint not null default 30,
  created_by   uuid not null references public.users(id),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create trigger guilds_updated_at
  before update on public.guilds
  for each row execute function public.set_updated_at();

create index idx_guilds_name on public.guilds(name);

create type public.guild_role as enum ('leader', 'officer', 'member');

create table public.guild_members (
  guild_id    uuid not null references public.guilds(id) on delete cascade,
  user_id     uuid not null references public.users(id) on delete cascade,
  role        public.guild_role not null default 'member',
  contribution bigint not null default 0,
  joined_at   timestamptz not null default now(),
  primary key (guild_id, user_id)
);

create index idx_guild_members_user_id on public.guild_members(user_id);

-- RLS
alter table public.visits enable row level security;
alter table public.guilds enable row level security;
alter table public.guild_members enable row level security;

create policy "visits_select_own"
  on public.visits for select
  using (
    host_user_id in (select id from public.users where auth_uid = auth.uid())
    or visitor_eidolon_id in (
      select e.id from public.eidolons e
      join public.users u on u.id = e.user_id
      where u.auth_uid = auth.uid()
    )
  );

create policy "visits_service_all"  on public.visits for all using (auth.role() = 'service_role');
create policy "guilds_select_all"   on public.guilds for select using (true);
create policy "guilds_service_all"  on public.guilds for all using (auth.role() = 'service_role');
create policy "guild_members_select_all" on public.guild_members for select using (true);
create policy "guild_members_service_all" on public.guild_members for all using (auth.role() = 'service_role');
