-- ── FUTURE SELF SIMULATIONS ───────────────────────────────────────────────────
-- On-demand simulations generated by the future-self edge function.
-- Separate from the `predictions` table (batch cron, JSON-heavy) to keep
-- the mobile-facing schema simple and query-friendly.

CREATE TABLE IF NOT EXISTS future_self_simulations (
  id                UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id           UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  horizon_months    INTEGER     NOT NULL CHECK (horizon_months IN (1, 3, 12, 36)),
  narrative         TEXT        NOT NULL,
  letter_text       TEXT,
  trajectory_score  FLOAT       CHECK (trajectory_score BETWEEN 1 AND 10),
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, horizon_months)
);

CREATE INDEX IF NOT EXISTS future_self_simulations_user
  ON future_self_simulations (user_id, horizon_months);

-- RLS
ALTER TABLE future_self_simulations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own simulations"
  ON future_self_simulations FOR SELECT
  USING (auth.uid() = (SELECT auth_id FROM users WHERE id = user_id));

CREATE POLICY "Service role can manage simulations"
  ON future_self_simulations FOR ALL
  USING (auth.role() = 'service_role');
