import { createClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'

export default async function OnboardingPage() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) redirect('/auth')

  return (
    <main className="min-h-screen flex items-center justify-center px-4">
      <div className="w-full max-w-lg space-y-8">
        <div className="text-center space-y-2">
          <h1 className="text-3xl font-semibold font-display">Welcome to ECHO</h1>
          <p className="text-echo-muted text-sm">
            Let&apos;s set up your memory layer.
          </p>
        </div>
        <div className="bg-echo-surface border border-echo rounded-2xl p-8">
          {/* E01-09: Multi-step onboarding wizard generated by Lovable */}
          {/* Step 1: Display name + timezone */}
          {/* Step 2: Primary goals */}
          {/* Step 3: Values discovery */}
          <p className="text-echo-muted text-sm text-center">
            Onboarding wizard — coming in E01-09
          </p>
        </div>
      </div>
    </main>
  )
}
