import { createClient } from '@/lib/supabase/server'
import { notFound } from 'next/navigation'
import type { Metadata } from 'next'

interface Props {
  params: Promise<{ code: string }>
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { code } = await params
  return {
    title: 'ECHO Identity',
    description: `An identity portrait generated by ECHO — AI memory layer`,
    openGraph: {
      title: 'My ECHO Identity',
      description: 'See who I am according to my AI memory layer.',
      url: `https://echo-self.app/identity/${code}`,
    },
  }
}

const TYPE_COLORS: Record<string, string> = {
  value:                '#7B6CF6',
  belief:               '#A89DF8',
  strength:             '#6CF6C8',
  core_desire:          '#F6A26C',
  core_fear:            '#F66C6C',
  behavioral_pattern:   '#6C9EF6',
  relationship_pattern: '#F6D46C',
}

const TYPE_LABELS: Record<string, string> = {
  value:                'Value',
  belief:               'Belief',
  strength:             'Strength',
  core_desire:          'Desire',
  core_fear:            'Fear',
  behavioral_pattern:   'Pattern',
  relationship_pattern: 'Relational',
}

export default async function IdentitySharePage({ params }: Props) {
  const { code } = await params
  const supabase = await createClient()

  const { data: share } = await supabase
    .from('identity_shares')
    .select('nodes_snapshot, updated_at')
    .eq('share_code', code)
    .maybeSingle()

  if (!share) notFound()

  const nodes = (share.nodes_snapshot as Array<{
    id: string
    type: string
    label: string
    confidence: number
    polarity: string
  }>) ?? []

  const date = new Date(share.updated_at).toLocaleDateString(undefined, {
    month: 'long',
    year: 'numeric',
  })

  return (
    <main className="min-h-screen bg-[#0A0B0F] flex items-center justify-center p-4">
      <div className="w-full max-w-sm space-y-6">
        {/* Identity card */}
        <div className="rounded-2xl bg-[#141620] border border-white/10 p-6 space-y-5">
          <div className="space-y-1">
            <p className="text-[10px] font-medium text-[#7B6CF6] uppercase tracking-widest">ECHO Identity</p>
            <p className="text-xs text-[#8B8FA8]">{date}</p>
          </div>

          <div className="space-y-2">
            {nodes.map(node => {
              const color = TYPE_COLORS[node.type] ?? '#8B8FA8'
              return (
                <div key={node.id} className="flex items-center gap-3">
                  <span
                    className="text-[10px] w-16 flex-shrink-0 text-right"
                    style={{ color: `${color}99` }}
                  >
                    {TYPE_LABELS[node.type] ?? node.type}
                  </span>
                  <span
                    className="text-sm font-medium"
                    style={{ color }}
                  >
                    {node.label}
                  </span>
                  <span className="ml-auto text-[10px] text-[#8B8FA8]">
                    {Math.round(node.confidence * 100)}%
                  </span>
                </div>
              )
            })}
          </div>

          <div className="pt-2 border-t border-white/5 flex items-center justify-between">
            <p className="text-[10px] text-[#8B8FA8]">
              {nodes.length} identity signals
            </p>
            <p className="text-[10px] text-[#7B6CF6] font-medium">echo-self.app</p>
          </div>
        </div>

        {/* CTA */}
        <div className="text-center space-y-3">
          <p className="text-sm text-[#8B8FA8]">
            What does your identity look like?
          </p>
          <a
            href="/"
            className="block w-full rounded-xl bg-[#7B6CF6] py-3 text-sm font-medium text-white text-center hover:opacity-90 transition-opacity"
          >
            Build your own Identity →
          </a>
        </div>
      </div>
    </main>
  )
}
