import React, { useState, useEffect, useCallback } from 'react';
import {
  View,
  Text,
  ScrollView,
  StyleSheet,
  Pressable,
  ActivityIndicator,
  Share,
  Alert,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import Animated, { FadeIn, FadeInDown } from 'react-native-reanimated';
import * as Haptics from 'expo-haptics';
import { supabase } from '../../services/supabase';
import { useAuthStore } from '../../store/auth';
import { Colors, Spacing } from '../../theme/tokens';

type Horizon = 1 | 3 | 12 | 36;

interface Simulation {
  id: string;
  horizon_months: Horizon;
  narrative: string;
  letter_text: string | null;
  trajectory_score: number | null;
  created_at: string;
}

// ─── Horizon selector ─────────────────────────────────────────────────────────
const HORIZONS: { value: Horizon; label: string; desc: string }[] = [
  { value: 1,  label: '1 month',  desc: 'Near future' },
  { value: 3,  label: '3 months', desc: 'Next quarter' },
  { value: 12, label: '1 year',   desc: 'Long view' },
  { value: 36, label: '3 years',  desc: 'Deep future' },
];

// ─── Trajectory score ring ────────────────────────────────────────────────────
function ScoreRing({ score }: { score: number }) {
  const pct = score / 10;
  const color = pct >= 0.7 ? Colors.success : pct >= 0.4 ? Colors.warning : Colors.error;
  return (
    <View style={styles.scoreRing}>
      <Text style={[styles.scoreValue, { color }]}>{score.toFixed(1)}</Text>
      <Text style={styles.scoreLabel}>Trajectory</Text>
    </View>
  );
}

// ─── Main screen ──────────────────────────────────────────────────────────────
export function FutureSelfScreen() {
  const { user } = useAuthStore();
  const [horizon, setHorizon] = useState<Horizon>(12);
  const [simulation, setSimulation] = useState<Simulation | null>(null);
  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [entryCount, setEntryCount] = useState(0);
  const [tab, setTab] = useState<'narrative' | 'letter'>('narrative');

  const MIN_ENTRIES = 10;

  const fetchSimulation = useCallback(async () => {
    if (!user?.id) return;
    setLoading(true);
    const { data } = await supabase
      .from('future_self_simulations')
      .select('*')
      .eq('user_id', user.id)
      .eq('horizon_months', horizon)
      .order('created_at', { ascending: false })
      .limit(1)
      .maybeSingle();
    setSimulation(data ?? null);
    setLoading(false);
  }, [user?.id, horizon]);

  const fetchEntryCount = useCallback(async () => {
    if (!user?.id) return;
    const { count } = await supabase
      .from('entries')
      .select('id', { count: 'exact', head: true })
      .eq('user_id', user.id);
    setEntryCount(count ?? 0);
  }, [user?.id]);

  useEffect(() => {
    fetchSimulation();
    fetchEntryCount();
  }, [fetchSimulation, fetchEntryCount]);

  async function handleGenerate() {
    if (entryCount < MIN_ENTRIES) {
      Alert.alert(
        'Not enough memories',
        `ECHO needs at least ${MIN_ENTRIES} entries to simulate your future. You have ${entryCount} so far. Keep writing!`,
      );
      return;
    }
    setGenerating(true);
    await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    try {
      const { data, error } = await supabase.functions.invoke('future-self', {
        body: { horizon_months: horizon, user_id: user?.id },
      });
      if (error) throw error;
      setSimulation(data as Simulation);
      await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    } catch (err) {
      Alert.alert('Could not generate', 'Please try again in a moment.');
    } finally {
      setGenerating(false);
    }
  }

  async function handleShare() {
    const text = tab === 'letter' && simulation?.letter_text
      ? simulation.letter_text
      : simulation?.narrative ?? '';
    await Share.share({
      message: `A message from my future self:\n\n${text}\n\n— Generated by ECHO`,
    });
  }

  return (
    <SafeAreaView style={styles.container} edges={['top']}>
      <ScrollView
        contentContainerStyle={styles.scroll}
        showsVerticalScrollIndicator={false}
      >
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.headerTitle}>Future Self</Text>
          <Text style={styles.headerSub}>Who are you becoming?</Text>
        </View>

        {/* Horizon selector */}
        <View style={styles.horizonRow}>
          {HORIZONS.map((h) => (
            <Pressable
              key={h.value}
              onPress={() => { setHorizon(h.value); setTab('narrative'); }}
              style={[styles.horizonChip, horizon === h.value && styles.horizonChipActive]}
            >
              <Text style={[styles.horizonLabel, horizon === h.value && styles.horizonLabelActive]}>
                {h.label}
              </Text>
              <Text style={[styles.horizonDesc, horizon === h.value && styles.horizonDescActive]}>
                {h.desc}
              </Text>
            </Pressable>
          ))}
        </View>

        {/* Entry count gate */}
        {entryCount < MIN_ENTRIES && (
          <Animated.View entering={FadeInDown.springify()} style={styles.gateCard}>
            <Text style={styles.gateIcon}>🌱</Text>
            <Text style={styles.gateTitle}>Keep writing</Text>
            <Text style={styles.gateSub}>
              {MIN_ENTRIES - entryCount} more {MIN_ENTRIES - entryCount === 1 ? 'entry' : 'entries'} needed to unlock your future self simulation.
            </Text>
            <View style={styles.progressBar}>
              <View style={[styles.progressFill, { flex: entryCount / MIN_ENTRIES }]} />
              <View style={{ flex: 1 - entryCount / MIN_ENTRIES }} />
            </View>
            <Text style={styles.progressText}>{entryCount} / {MIN_ENTRIES}</Text>
          </Animated.View>
        )}

        {/* Loading state */}
        {loading && (
          <View style={styles.center}>
            <ActivityIndicator color={Colors.indigo} />
          </View>
        )}

        {/* Simulation result */}
        {!loading && simulation && (
          <Animated.View entering={FadeIn.springify()}>
            {/* Score + tab switcher */}
            <View style={styles.simHeader}>
              {simulation.trajectory_score != null && (
                <ScoreRing score={simulation.trajectory_score} />
              )}
              {simulation.letter_text && (
                <View style={styles.tabRow}>
                  {(['narrative', 'letter'] as const).map((t) => (
                    <Pressable
                      key={t}
                      onPress={() => setTab(t)}
                      style={[styles.tabBtn, tab === t && styles.tabBtnActive]}
                    >
                      <Text style={[styles.tabBtnText, tab === t && styles.tabBtnTextActive]}>
                        {t === 'narrative' ? 'Vision' : 'Letter'}
                      </Text>
                    </Pressable>
                  ))}
                </View>
              )}
            </View>

            <View style={styles.simCard}>
              <Text style={styles.simDate}>
                Generated {new Date(simulation.created_at).toLocaleDateString(undefined, {
                  month: 'long', day: 'numeric', year: 'numeric'
                })}
              </Text>
              <Text style={styles.simText}>
                {tab === 'letter' && simulation.letter_text
                  ? simulation.letter_text
                  : simulation.narrative}
              </Text>
            </View>

            <View style={styles.simActions}>
              <Pressable style={styles.shareBtn} onPress={handleShare}>
                <Text style={styles.shareBtnText}>Share →</Text>
              </Pressable>
              <Pressable style={styles.regenerateBtn} onPress={handleGenerate} disabled={generating}>
                <Text style={styles.regenerateBtnText}>
                  {generating ? 'Generating…' : 'Regenerate'}
                </Text>
              </Pressable>
            </View>
          </Animated.View>
        )}

        {/* Empty / generate CTA */}
        {!loading && !simulation && entryCount >= MIN_ENTRIES && (
          <Animated.View entering={FadeInDown.springify()} style={styles.generateCard}>
            <Text style={styles.generateIcon}>🔮</Text>
            <Text style={styles.generateTitle}>
              Simulate your {horizon === 1 ? '1-month' : horizon === 3 ? '3-month' : horizon === 12 ? '1-year' : '3-year'} future
            </Text>
            <Text style={styles.generateSub}>
              ECHO will analyse your {entryCount} memories and show you who you&apos;re becoming.
            </Text>
            <Pressable
              style={[styles.generateBtn, generating && styles.generateBtnDisabled]}
              onPress={handleGenerate}
              disabled={generating}
            >
              {generating ? (
                <ActivityIndicator color="#fff" size="small" />
              ) : (
                <Text style={styles.generateBtnText}>Generate my future →</Text>
              )}
            </Pressable>
          </Animated.View>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

// ─── Styles ───────────────────────────────────────────────────────────────────
const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.black },
  scroll: { padding: Spacing.md, paddingBottom: 120 },
  center: { paddingVertical: 60, alignItems: 'center' },

  header: { marginBottom: Spacing.lg },
  headerTitle: { fontSize: 28, fontWeight: '700', color: Colors.textPrimary, letterSpacing: -0.5 },
  headerSub: { fontSize: 14, color: Colors.textSecondary, marginTop: 4 },

  horizonRow: { flexDirection: 'row', gap: Spacing.sm, marginBottom: Spacing.lg },
  horizonChip: {
    flex: 1,
    backgroundColor: Colors.surface1,
    borderRadius: 12,
    padding: Spacing.sm,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.border0,
  },
  horizonChipActive: {
    backgroundColor: `${Colors.indigo}20`,
    borderColor: `${Colors.indigo}60`,
  },
  horizonLabel: { fontSize: 12, fontWeight: '600', color: Colors.textSecondary },
  horizonLabelActive: { color: Colors.indigo },
  horizonDesc: { fontSize: 9, color: Colors.textTertiary, marginTop: 2 },
  horizonDescActive: { color: `${Colors.indigo}90` },

  gateCard: {
    backgroundColor: Colors.surface1,
    borderRadius: 16,
    padding: Spacing.lg,
    alignItems: 'center',
    gap: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.border0,
  },
  gateIcon: { fontSize: 40 },
  gateTitle: { fontSize: 18, fontWeight: '700', color: Colors.textPrimary },
  gateSub: { fontSize: 14, color: Colors.textSecondary, textAlign: 'center', lineHeight: 20 },
  progressBar: {
    flexDirection: 'row',
    height: 4,
    width: '100%',
    borderRadius: 2,
    overflow: 'hidden',
    backgroundColor: Colors.surface2,
    marginTop: Spacing.sm,
  },
  progressFill: { backgroundColor: Colors.indigo, borderRadius: 2 },
  progressText: { fontSize: 11, color: Colors.textTertiary },

  simHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: Spacing.md },
  scoreRing: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: Colors.surface1,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.border1,
  },
  scoreValue: { fontSize: 18, fontWeight: '800' },
  scoreLabel: { fontSize: 8, color: Colors.textTertiary, letterSpacing: 0.5 },

  tabRow: { flexDirection: 'row', gap: Spacing.xs },
  tabBtn: {
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    borderRadius: 8,
    backgroundColor: Colors.surface1,
    borderWidth: 1,
    borderColor: Colors.border0,
  },
  tabBtnActive: { backgroundColor: `${Colors.indigo}20`, borderColor: `${Colors.indigo}60` },
  tabBtnText: { fontSize: 12, color: Colors.textSecondary },
  tabBtnTextActive: { color: Colors.indigo, fontWeight: '600' },

  simCard: {
    backgroundColor: Colors.surface1,
    borderRadius: 16,
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.border0,
    marginBottom: Spacing.md,
  },
  simDate: { fontSize: 10, color: Colors.textTertiary, marginBottom: Spacing.sm, letterSpacing: 0.5 },
  simText: { fontSize: 15, color: Colors.textPrimary, lineHeight: 26 },

  simActions: { flexDirection: 'row', gap: Spacing.sm },
  shareBtn: {
    flex: 1,
    backgroundColor: Colors.indigo,
    borderRadius: 12,
    padding: Spacing.md,
    alignItems: 'center',
  },
  shareBtnText: { fontSize: 14, fontWeight: '600', color: '#fff' },
  regenerateBtn: {
    backgroundColor: Colors.surface1,
    borderRadius: 12,
    padding: Spacing.md,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.border1,
  },
  regenerateBtnText: { fontSize: 14, color: Colors.textSecondary },

  generateCard: {
    backgroundColor: Colors.surface1,
    borderRadius: 20,
    padding: Spacing.lg,
    alignItems: 'center',
    gap: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.border0,
  },
  generateIcon: { fontSize: 56 },
  generateTitle: { fontSize: 20, fontWeight: '700', color: Colors.textPrimary, textAlign: 'center' },
  generateSub: { fontSize: 14, color: Colors.textSecondary, textAlign: 'center', lineHeight: 22 },
  generateBtn: {
    backgroundColor: Colors.indigo,
    borderRadius: 14,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    width: '100%',
    alignItems: 'center',
  },
  generateBtnDisabled: { opacity: 0.5 },
  generateBtnText: { fontSize: 16, fontWeight: '700', color: '#fff' },
});
