// Auto-generated by: npm run db:types
// Run `supabase gen types typescript --local > packages/supabase/src/types/database.ts` to regenerate.
// Do NOT edit manually.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          display_name: string | null
          avatar_url: string | null
          timezone: string
          onboarding_completed: boolean
          onboarding_data: Json | null
          current_streak: number
          longest_streak: number
          last_entry_date: string | null
          total_entries: number
          total_echo_sessions: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          display_name?: string | null
          avatar_url?: string | null
          timezone?: string
          onboarding_completed?: boolean
          onboarding_data?: Json | null
          current_streak?: number
          longest_streak?: number
          last_entry_date?: string | null
          total_entries?: number
          total_echo_sessions?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          display_name?: string | null
          avatar_url?: string | null
          timezone?: string
          onboarding_completed?: boolean
          onboarding_data?: Json | null
          current_streak?: number
          longest_streak?: number
          last_entry_date?: string | null
          total_entries?: number
          total_echo_sessions?: number
          created_at?: string
          updated_at?: string
        }
      }
      journal_entries: {
        Row: {
          id: string
          user_id: string
          content: string
          content_type: 'text' | 'voice' | 'echo_session'
          title: string | null
          emotions: Json | null
          ai_processed: boolean
          ai_processed_at: string | null
          word_count: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          content: string
          content_type?: 'text' | 'voice' | 'echo_session'
          title?: string | null
          emotions?: Json | null
          ai_processed?: boolean
          ai_processed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          content?: string
          content_type?: 'text' | 'voice' | 'echo_session'
          title?: string | null
          emotions?: Json | null
          ai_processed?: boolean
          ai_processed_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      memories: {
        Row: {
          id: string
          user_id: string
          content: string
          embedding: string | null  // vector(3072) stored as string
          type: 'belief' | 'value' | 'core_fear' | 'core_desire' | 'behavioral_pattern' | 'relationship_pattern' | 'strength' | 'event'
          emotion: string | null
          confidence: number
          tags: string[]
          source_entry_id: string | null
          is_archived: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          content: string
          embedding?: string | null
          type: 'belief' | 'value' | 'core_fear' | 'core_desire' | 'behavioral_pattern' | 'relationship_pattern' | 'strength' | 'event'
          emotion?: string | null
          confidence?: number
          tags?: string[]
          source_entry_id?: string | null
          is_archived?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          content?: string
          embedding?: string | null
          type?: 'belief' | 'value' | 'core_fear' | 'core_desire' | 'behavioral_pattern' | 'relationship_pattern' | 'strength' | 'event'
          emotion?: string | null
          confidence?: number
          tags?: string[]
          source_entry_id?: string | null
          is_archived?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      identity_nodes: {
        Row: {
          id: string
          user_id: string
          type: 'belief' | 'core_fear' | 'core_desire' | 'value' | 'behavioral_pattern' | 'relationship_pattern' | 'strength'
          label: string
          description: string | null
          evidence: string[]
          confidence: number
          polarity: 'positive' | 'negative' | 'neutral'
          active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: 'belief' | 'core_fear' | 'core_desire' | 'value' | 'behavioral_pattern' | 'relationship_pattern' | 'strength'
          label: string
          description?: string | null
          evidence?: string[]
          confidence?: number
          polarity?: 'positive' | 'negative' | 'neutral'
          active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          type?: 'belief' | 'core_fear' | 'core_desire' | 'value' | 'behavioral_pattern' | 'relationship_pattern' | 'strength'
          label?: string
          description?: string | null
          evidence?: string[]
          confidence?: number
          polarity?: 'positive' | 'negative' | 'neutral'
          active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      future_self_predictions: {
        Row: {
          id: string
          user_id: string
          timeframe: '30d' | '90d' | '365d'
          headline: string
          narrative: string
          opportunity: string
          risk: string
          confidence: number
          share_snippet: string
          generated_at: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          timeframe: '30d' | '90d' | '365d'
          headline: string
          narrative: string
          opportunity: string
          risk: string
          confidence: number
          share_snippet: string
          generated_at?: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          timeframe?: '30d' | '90d' | '365d'
          headline?: string
          narrative?: string
          opportunity?: string
          risk?: string
          confidence?: number
          share_snippet?: string
          generated_at?: string
          created_at?: string
        }
      }
      echo_sessions: {
        Row: {
          id: string
          user_id: string
          title: string | null
          duration_seconds: number | null
          message_count: number
          emotion_summary: Json | null
          ended_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title?: string | null
          duration_seconds?: number | null
          message_count?: number
          emotion_summary?: Json | null
          ended_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          title?: string | null
          duration_seconds?: number | null
          message_count?: number
          emotion_summary?: Json | null
          ended_at?: string | null
          created_at?: string
        }
      }
      echo_messages: {
        Row: {
          id: string
          session_id: string
          user_id: string
          role: 'user' | 'assistant'
          content: string
          emotion_tags: string[]
          created_at: string
        }
        Insert: {
          id?: string
          session_id: string
          user_id: string
          role: 'user' | 'assistant'
          content: string
          emotion_tags?: string[]
          created_at?: string
        }
        Update: {
          id?: string
          session_id?: string
          user_id?: string
          role?: 'user' | 'assistant'
          content?: string
          emotion_tags?: string[]
          created_at?: string
        }
      }
      subscriptions: {
        Row: {
          id: string
          user_id: string
          plan: 'free' | 'pro'
          status: 'active' | 'trialing' | 'past_due' | 'canceled' | 'incomplete'
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          stripe_price_id: string | null
          trial_ends_at: string | null
          current_period_end: string | null
          entries_this_month: number
          echo_sessions_this_month: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          plan?: 'free' | 'pro'
          status?: 'active' | 'trialing' | 'past_due' | 'canceled' | 'incomplete'
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          stripe_price_id?: string | null
          trial_ends_at?: string | null
          current_period_end?: string | null
          entries_this_month?: number
          echo_sessions_this_month?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          plan?: 'free' | 'pro'
          status?: 'active' | 'trialing' | 'past_due' | 'canceled' | 'incomplete'
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          stripe_price_id?: string | null
          trial_ends_at?: string | null
          current_period_end?: string | null
          entries_this_month?: number
          echo_sessions_this_month?: number
          created_at?: string
          updated_at?: string
        }
      }
      referrals: {
        Row: {
          id: string
          referrer_id: string
          referred_id: string | null
          code: string
          status: 'pending' | 'signed_up' | 'converted'
          reward_granted: boolean
          created_at: string
          converted_at: string | null
        }
        Insert: {
          id?: string
          referrer_id: string
          referred_id?: string | null
          code: string
          status?: 'pending' | 'signed_up' | 'converted'
          reward_granted?: boolean
          created_at?: string
          converted_at?: string | null
        }
        Update: {
          id?: string
          referrer_id?: string
          referred_id?: string | null
          code?: string
          status?: 'pending' | 'signed_up' | 'converted'
          reward_granted?: boolean
          created_at?: string
          converted_at?: string | null
        }
      }
      notification_preferences: {
        Row: {
          id: string
          user_id: string
          onesignal_player_id: string | null
          insight_ready: boolean
          streak_reminder: boolean
          weekly_summary: boolean
          marketing: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          onesignal_player_id?: string | null
          insight_ready?: boolean
          streak_reminder?: boolean
          weekly_summary?: boolean
          marketing?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          onesignal_player_id?: string | null
          insight_ready?: boolean
          streak_reminder?: boolean
          weekly_summary?: boolean
          marketing?: boolean
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: Record<string, never>
    Functions: {
      retrieve_memories: {
        Args: {
          p_user_id: string
          p_query_embedding: string
          p_top_k?: number
          p_min_similarity?: number
          p_types?: string[]
        }
        Returns: {
          id: string
          content: string
          type: string
          emotion: string | null
          confidence: number
          similarity: number
          created_at: string
        }[]
      }
      find_similar_memories: {
        Args: {
          p_user_id: string
          p_content_embedding: string
          p_threshold?: number
        }
        Returns: {
          id: string
          content: string
          similarity: number
        }[]
      }
      get_users_for_prediction: {
        Args: Record<string, never>
        Returns: { user_id: string }[]
      }
      can_create_journal_entry: {
        Args: { p_user_id: string }
        Returns: boolean
      }
    }
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']
export type Inserts<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']
export type Updates<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']
